version: 'version 1.0.0'

networks:
  img2map-network:
    driver: bridge
  #This is the network that the containers will use to communicate with each other

services:
  img2map-api:
    #Uvicorn server running python FastAPI
    container_name: Img2Map-API
    env_file:
      - ./backend/.env
    environment:
      - PORT=8000
      - ENVIRONMENT=production
      - CORS_ORIGINS=http://localhost:3000,next-app:3000,
    build:
      context: ./backend
      dockerfile: ./docker/prod.Dockerfile
    expose:
      - "8000:8000"
    networks:
      - img2map-network
  
  next-app:
    container_name: Img2Map-Website
    build:
      context: ./frontend
      dockerfile: ./docker/prod.Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=img2map-api:8000
    env_file:
      - ./frontend/.env
    networks:
      - img2map-network

  