version: 'version 1.0.1-dev'

networks:
  img2map-network:
    driver: bridge
  backend-network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: Img2Map-postgres
    restart: always
    environment:
      POSTGRES_USER: img2map
      POSTGRES_PASSWORD: password
      POSTGRES_DB: img2map
    ports:
      - "5432:5432"
    networks:
      - backend-network
  
  img2map-api:
    #Uvicorn server running python FastAPI
    container_name: Img2Map-API

    build:
      context: ../
      dockerfile: /docker/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - img2map-network
      - backend-network
